/**
 * One-off image optimizer.
 *
 * The project screenshots were committed at full device resolution (1320x2868,
 * up to 2.6 MB each) and rendered inside a ~240px device frame, so the browser
 * downloaded roughly 9 MB to paint a few hundred kilobytes of pixels. On a
 * throttled connection the frame stayed black for seconds.
 *
 * This rewrites every source image as WebP at ~2x its rendered size, and emits
 * a tiny blurred placeholder per file so a frame is never empty while the real
 * image arrives.
 *
 *   node scripts/optimize-images.mjs           # convert, keep originals
 *   node scripts/optimize-images.mjs --delete  # convert, remove the originals
 *
 * Re-running is safe: it always regenerates from whatever source files remain.
 */

import { readdir, readFile, writeFile, unlink, stat } from "node:fs/promises";
import { join, dirname, extname, basename } from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const PROJECTS_DIR = join(ROOT, "src/assets/projects");

const SOURCE_EXT = new Set([".png", ".jpg", ".jpeg"]);

/** Rendered at min(240px, 58vw) in a phone frame, so 640 covers 2x DPR with room. */
const SCREEN_WIDTH = 640;
/** Hero photo is clamp(180px, 22vw, 280px) wide. */
const PHOTO_WIDTH = 600;
const QUALITY = 82;

/** Wide enough to carry colour and rough shape, small enough to inline. */
const LQIP_WIDTH = 24;

const kb = (n) => `${(n / 1024).toFixed(0)} kB`;

async function convert(srcPath, width) {
  const outPath = join(dirname(srcPath), `${basename(srcPath, extname(srcPath))}.webp`);
  const before = (await stat(srcPath)).size;

  await sharp(srcPath)
    .resize({ width, withoutEnlargement: true })
    .webp({ quality: QUALITY })
    .toFile(outPath);

  const after = (await stat(outPath)).size;

  console.log(
    `  ${basename(srcPath)} -> ${basename(outPath)}  ${kb(before)} -> ${kb(after)}` +
      `  (-${(100 - (after / before) * 100).toFixed(0)}%)`
  );

  return { outPath, before, after };
}

async function lqipFor(path) {
  const buf = await sharp(path).resize({ width: LQIP_WIDTH }).webp({ quality: 40 }).toBuffer();
  return `data:image/webp;base64,${buf.toString("base64")}`;
}

/**
 * Always regenerated by scanning the .webp files that exist now, so this stays
 * correct whether or not the original sources are still around.
 */
async function writeLqipModule() {
  const map = {};
  for (const entry of await readdir(PROJECTS_DIR, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const dir = join(PROJECTS_DIR, entry.name);
    for (const file of (await readdir(dir)).sort()) {
      if (extname(file) !== ".webp") continue;
      map[`${entry.name}/${file}`] = await lqipFor(join(dir, file));
    }
  }

  const body = Object.entries(map)
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
    .join("\n");

  await writeFile(
    join(PROJECTS_DIR, "lqip.ts"),
    `// Generated by scripts/optimize-images.mjs. Do not edit by hand.\n` +
      `// Tiny blurred stand-ins keyed by "<slug>/<file>", so a device frame is\n` +
      `// never empty while the real screenshot loads.\n\n` +
      `export const LQIP: Record<string, string> = {\n${body}\n};\n`
  );

  return Object.keys(map).length;
}

async function main() {
  const del = process.argv.includes("--delete");
  let totalBefore = 0;
  let totalAfter = 0;
  const converted = [];

  console.log("\nProject screenshots:");
  const slugs = await readdir(PROJECTS_DIR, { withFileTypes: true });
  for (const entry of slugs) {
    if (!entry.isDirectory()) continue;
    const dir = join(PROJECTS_DIR, entry.name);
    for (const file of await readdir(dir)) {
      if (!SOURCE_EXT.has(extname(file).toLowerCase())) continue;
      const src = join(dir, file);
      const { before, after } = await convert(src, SCREEN_WIDTH);
      totalBefore += before;
      totalAfter += after;
      converted.push(src);
    }
  }
  if (converted.length === 0) console.log("  (nothing to convert)");

  console.log("\nHero photos:");
  for (const name of ["me_night.png", "me_day.jpeg"]) {
    const src = join(ROOT, "src/assets", name);
    try {
      await stat(src);
    } catch {
      continue;
    }
    const { before, after } = await convert(src, PHOTO_WIDTH);
    totalBefore += before;
    totalAfter += after;
    converted.push(src);
  }

  const count = await writeLqipModule();
  console.log(`\nWrote ${count} placeholders to projects/lqip.ts`);

  if (del && converted.length) {
    for (const src of converted) await unlink(src);
    console.log(`Deleted ${converted.length} source files.`);
  } else if (converted.length) {
    console.log("Originals kept. Re-run with --delete to remove them.");
  }

  if (totalBefore) {
    console.log(
      `\nTotal: ${kb(totalBefore)} -> ${kb(totalAfter)}  ` +
        `(-${(100 - (totalAfter / totalBefore) * 100).toFixed(1)}%)\n`
    );
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
